[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "prague"
optimizer = true
optimizer_runs = 200
via_ir = true

# Monad Mainnet
[rpc_endpoints]
monad_mainnet = "${MONAD_RPC_URL}"

[etherscan]
monad_mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://monad.socialscan.io/api" }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
